namespace KKL.WordStudio.UI.Views;

using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Threading;

public partial class ExcelWorkspaceView
{
    private void WorkingDataGrid_AutoGeneratedColumnsV23(object? sender, EventArgs e)
    {
        foreach (var column in WorkingDataGrid.Columns)
        {
            column.CanUserSort = false;
            var identity = GetColumnIdentity(column);
            if (string.IsNullOrWhiteSpace(identity)) continue;

            var option = _viewModel.GetOrCreateTransferColumnOption(identity);
            var letter = _viewModel.ResolveDisplayColumnLetter(identity, column.DisplayIndex);

            var panel = new StackPanel
            {
                Orientation = Orientation.Horizontal,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center
            };
            var include = new CheckBox
            {
                IsChecked = option?.IsIncluded ?? false,
                Focusable = false,
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(0, 0, 5, 0),
                ToolTip = "Bu sütunu Word tablosuna aktar"
            };
            include.Checked += (_, _) => _viewModel.SetColumnIncluded(identity, true);
            include.Unchecked += (_, _) => _viewModel.SetColumnIncluded(identity, false);
            panel.Children.Add(include);
            panel.Children.Add(new TextBlock
            {
                Text = letter,
                FontWeight = FontWeights.SemiBold,
                VerticalAlignment = VerticalAlignment.Center
            });

            column.Header = panel;
            column.HeaderStringFormat = null;
        }

        SynchronizeTransferColumnOrder();
    }

    private void SynchronizeTransferColumnOrder()
    {
        var orderedIdentities = WorkingDataGrid.Columns
            .OrderBy(column => column.DisplayIndex)
            .Select(GetColumnIdentity)
            .Where(identity => !string.IsNullOrWhiteSpace(identity))
            .Cast<string>()
            .ToList();
        _viewModel.SetColumnDisplayOrder(orderedIdentities);
    }

    private void WorkingDataGrid_CellEditEndingV23(object sender, DataGridCellEditEndingEventArgs e)
    {
        if (e.EditAction != DataGridEditAction.Commit || e.EditingElement is not TextBox editor)
            return;

        var columnIdentity = GetColumnIdentity(e.Column);
        var rowIndex = WorkingDataGrid.Items.IndexOf(e.Row.Item);
        if (columnIdentity is null || rowIndex < 0)
            return;

        var value = editor.Text;
        e.Cancel = true;
        ArmGridKeyboardRestore();

        // Replacing PreviewTable while WPF is still completing CellEditEnding
        // can leave DataGrid's internal row/cell indexes stale. Let the current
        // edit transaction unwind first, then cancel the visual edit and mutate
        // the project-owned working data on the same UI dispatcher.
        Dispatcher.BeginInvoke(
            DispatcherPriority.Background,
            new Action(() => _ = CommitCellEditAfterGridSettlesAsync(rowIndex, columnIdentity, value)));
    }

    private async Task CommitCellEditAfterGridSettlesAsync(
        int rowIndex,
        string columnIdentity,
        string value)
    {
        try
        {
            WorkingDataGrid.CancelEdit(DataGridEditingUnit.Cell);
            WorkingDataGrid.CancelEdit(DataGridEditingUnit.Row);
            await _viewModel.CommitGridCellEditAsync(rowIndex, columnIdentity, value);
        }
        catch (Exception exception)
        {
            _restoreGridFocusAfterPreviewRefresh = false;
            _viewModel.StatusText = $"Hücre güncellenemedi: {exception.Message}";
        }
    }

    private async void ClearCellsV23_Click(object sender, RoutedEventArgs e) =>
        await _viewModel.ClearGridCellsAsync(GetSelectedGridCells());

    private async void PasteV23_Click(object sender, RoutedEventArgs e) =>
        await PasteFromClipboardV23Async();

    private void RowHeaderV23_PreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (sender is not DataGridRowHeader header) return;
        ActivateRowHeader(header);
        var targetRows = GetContextRowTargets(_activeRowDisplayIndex);
        var menu = new ContextMenu();
        menu.Items.Add(CreateMenuItem("Üste Satır Ekle", async () => await _viewModel.InsertGridRowRelativeAsync(_activeRowDisplayIndex, below: false)));
        menu.Items.Add(CreateMenuItem("Alta Satır Ekle", async () => await _viewModel.InsertGridRowRelativeAsync(_activeRowDisplayIndex, below: true)));
        menu.Items.Add(new Separator());
        menu.Items.Add(CreateMenuItem("Satırı Sil", async () => await _viewModel.DeleteGridRowsAsync(targetRows)));
        menu.Items.Add(CreateMenuItem("Satırı Temizle", async () => await _viewModel.ClearGridRowsAsync(targetRows)));
        header.ContextMenu = menu;
        menu.IsOpen = true;
        e.Handled = true;
    }

    private void CellV23_PreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (sender is not DataGridCell cell) return;
        _interactionContext = GridInteractionContext.Cell;
        _activeRowDisplayIndex = WorkingDataGrid.Items.IndexOf(cell.DataContext);
        _activeColumnIdentity = GetColumnIdentity(cell.Column);
        if (_activeRowDisplayIndex < 0 || _activeColumnIdentity is null) return;

        var info = new DataGridCellInfo(cell.DataContext, cell.Column);
        WorkingDataGrid.CurrentCell = info;
        if (!WorkingDataGrid.SelectedCells.Contains(info))
        {
            WorkingDataGrid.UnselectAllCells();
            cell.IsSelected = true;
        }

        var menu = new ContextMenu();
        menu.Items.Add(CreateMenuItem("Kopyala", () =>
        {
            CopySelectionToClipboard();
            return Task.CompletedTask;
        }));
        menu.Items.Add(CreateMenuItem("Yapıştır", PasteFromClipboardV23Async));
        menu.Items.Add(CreateMenuItem("Temizle", async () => await _viewModel.ClearGridCellsAsync(GetSelectedGridCells())));
        cell.ContextMenu = menu;
        menu.IsOpen = true;
        e.Handled = true;
    }

    private async void WorkingDataGridV23_PreviewKeyDown(object sender, KeyEventArgs e)
    {
        var control = Keyboard.Modifiers.HasFlag(ModifierKeys.Control);

        if (control && e.Key == Key.Z)
        {
            e.Handled = true;
            if (_viewModel.UndoCommand.CanExecute(null)) _viewModel.UndoCommand.Execute(null);
            return;
        }

        if (control && e.Key == Key.Y)
        {
            e.Handled = true;
            if (_viewModel.RedoCommand.CanExecute(null)) _viewModel.RedoCommand.Execute(null);
            return;
        }

        if (control && IsPlusKey(e.Key))
        {
            e.Handled = true;
            switch (_interactionContext)
            {
                case GridInteractionContext.RowHeader when _activeRowDisplayIndex >= 0:
                    await _viewModel.InsertGridRowRelativeAsync(_activeRowDisplayIndex, below: false);
                    break;
                case GridInteractionContext.ColumnHeader when _activeColumnIdentity is not null:
                    await _viewModel.InsertColumnRelativeAsync(_activeColumnIdentity, right: false);
                    break;
                default:
                    _viewModel.ShowHeaderSelectionHint();
                    break;
            }
            return;
        }

        if (control && IsMinusKey(e.Key))
        {
            e.Handled = true;
            switch (_interactionContext)
            {
                case GridInteractionContext.RowHeader when _activeRowDisplayIndex >= 0:
                    await _viewModel.DeleteGridRowsAsync(GetContextRowTargets(_activeRowDisplayIndex));
                    break;
                case GridInteractionContext.ColumnHeader when _activeColumnIdentity is not null:
                    await _viewModel.DeleteColumnsByIdentityAsync(GetContextColumnTargets(_activeColumnIdentity));
                    break;
                default:
                    _viewModel.ShowHeaderSelectionHint();
                    break;
            }
            return;
        }

        if (e.Key == Key.Delete)
        {
            e.Handled = true;
            await _viewModel.ClearGridCellsAsync(GetSelectedGridCells());
            return;
        }

        if (control && e.Key == Key.C)
        {
            e.Handled = true;
            CopySelectionToClipboard();
            return;
        }

        if (control && e.Key == Key.V)
        {
            e.Handled = true;
            await PasteFromClipboardV23Async();
        }
    }

    private async Task PasteFromClipboardV23Async()
    {
        if (!Clipboard.ContainsText()) return;
        var rowIndex = GetCurrentRowIndex();
        var columnIdentity = GetCurrentColumnIdentity();
        if (rowIndex < 0 || columnIdentity is null) return;
        await _viewModel.PasteGridClipboardAsync(rowIndex, columnIdentity, Clipboard.GetText(TextDataFormat.Text));
    }
}