namespace KKL.WordStudio.Architecture.Tests;

using Xunit;

public sealed class Sprint23CurrentContractCharacterizationTests
{
    [Fact]
    public void ExcelWorkspace_CurrentlyHostsMappingDrawerRangeEditorAndLegacyTransferChoices()
    {
        var root = SolutionRootLocator.Find();
        var xaml = Read(root, "src", "KKL.WordStudio.UI", "Views", "ExcelWorkspaceView.xaml");

        Assert.DoesNotContain("Content=\"Sütunları Eşle\"", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("SÜTUNLARI SEÇ VE EŞLE", xaml, StringComparison.Ordinal);
        Assert.Contains("Content=\"Veri Aralığını Düzenle\"", xaml, StringComparison.Ordinal);
        Assert.Contains("Command=\"{Binding OpenTransferPlacementCommand}\"", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("Veriyi Yeniden Bağla (sütunları koru)", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("Sütunları Kaynaktan Yenile ve Bağla", xaml, StringComparison.Ordinal);
    }

    [Fact]
    public void Transfer_CurrentlyMutatesImmediatelyAndHasNoEditablePlacementOutline()
    {
        var root = SolutionRootLocator.Find();
        var xaml = Read(root, "src", "KKL.WordStudio.UI", "Views", "ExcelWorkspaceView.xaml");
        var placementViewModel = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "ExcelWorkspaceViewModel.TransferPlacement.cs");
        var coordinator = Read(root, "src", "KKL.WordStudio.Application", "Transfer", "ExcelTransferPlacementCoordinator.cs");

        Assert.Contains("Onayla ve Önizle", xaml, StringComparison.Ordinal);
        Assert.Contains("PlacementHeadingText", xaml, StringComparison.Ordinal);
        Assert.Contains("PlacementAltHeadingText", xaml, StringComparison.Ordinal);
        Assert.Contains("PlacementTableName", xaml, StringComparison.Ordinal);
        Assert.Contains("ExcelTransferPlacementCoordinator.Transfer", placementViewModel, StringComparison.Ordinal);
        Assert.Contains("RollBack(body.Root, created)", coordinator, StringComparison.Ordinal);
    }

    [Fact]
    public void WorkingDataGrid_CurrentlyReplacesExcelLettersWithWorkingHeadersAndDoesNotDisableSorting()
    {
        var root = SolutionRootLocator.Find();
        var xaml = Read(root, "src", "KKL.WordStudio.UI", "Views", "ExcelWorkspaceView.xaml");
        var sprint23CodeBehind = Read(root, "src", "KKL.WordStudio.UI", "Views", "ExcelWorkspaceView.Sprint23.cs");

        Assert.Contains("AutoGenerateColumns=\"True\"", xaml, StringComparison.Ordinal);
        Assert.Contains("CanUserSortColumns=\"False\"", xaml, StringComparison.Ordinal);
        Assert.Contains("AutoGeneratedColumns=\"WorkingDataGrid_AutoGeneratedColumnsV23\"", xaml, StringComparison.Ordinal);
        Assert.Contains("ResolveDisplayColumnLetter", sprint23CodeBehind, StringComparison.Ordinal);
        Assert.Contains("column.CanUserSort = false;", sprint23CodeBehind, StringComparison.Ordinal);
        Assert.Contains("SetColumnIncluded", sprint23CodeBehind, StringComparison.Ordinal);
    }

    [Fact]
    public void MainWindow_CurrentlyUsesFixedExcelPreviewDockColumnsAndShowsNewOpenCommands()
    {
        var root = SolutionRootLocator.Find();
        var xaml = Read(root, "src", "KKL.WordStudio.UI", "MainWindow.xaml");

        // The test name remains stable for the baseline inventory, while the
        // assertions now describe the accepted Sprint 23 responsive-shell contract.
        Assert.DoesNotContain("Content=\"＋ Yeni\"", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("Content=\"Aç\"", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("Content=\"Kaydet\"", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("Header=\"Farklı Kaydet\"", xaml, StringComparison.Ordinal);
        Assert.Contains("Content=\"Word Dosyası Oluştur\"", xaml, StringComparison.Ordinal);
        Assert.Contains("x:Name=\"ReportPaneShell\"", xaml, StringComparison.Ordinal);
        Assert.Contains("x:Name=\"ReportPaneToggleButton\"", xaml, StringComparison.Ordinal);
        Assert.Contains("x:Name=\"ReportPaneColumn\" Width=\"Auto\"", xaml, StringComparison.Ordinal);
        Assert.Contains("<ContentControl x:Name=\"ExcelWorkspaceHost\" Grid.Column=\"0\" />", xaml, StringComparison.Ordinal);
        Assert.Contains("<ContentControl x:Name=\"PreviewHost\" Grid.Column=\"0\" />", xaml, StringComparison.Ordinal);
        Assert.Contains("<ContentControl x:Name=\"ContextDockHost\" Grid.Column=\"2\" />", xaml, StringComparison.Ordinal);
        Assert.Contains("<ColumnDefinition x:Name=\"DockColumn\" Width=\"350\" />", xaml, StringComparison.Ordinal);
    }

    [Fact]
    public void ContentsAndWarnings_CurrentlyProjectFlatReportOrderAndUseSingleLevelPreviewDiagnostics()
    {
        var root = SolutionRootLocator.Find();
        var contents = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "ContentsViewModel.cs");
        var structure = Read(root, "src", "KKL.WordStudio.Application", "Structure", "ReportStructureService.cs");
        var warnings = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "WarningCenterViewModel.cs");
        var summaries = Read(root, "src", "KKL.WordStudio.Application", "Preview", "PreviewDiagnosticSummaryService.cs");

        Assert.Contains("a flat sequence of Heading/AltHeading/Table", contents, StringComparison.Ordinal);
        Assert.Contains("section.Root.Children", contents, StringComparison.Ordinal);
        Assert.Contains("never introduces a second outline", structure, StringComparison.Ordinal);

        // The stable test name is retained for inventory continuity. The accepted
        // warning contract now projects raw diagnostics into grouped, severity-aware
        // actions without changing the report outline or introducing a second validator.
        Assert.Contains("public int Count => Items.Count;", warnings, StringComparison.Ordinal);
        Assert.Contains("public int TotalCount => _store.Count;", warnings, StringComparison.Ordinal);
        Assert.Contains("WarningCenterFilter", warnings, StringComparison.Ordinal);
        Assert.Contains("_store.Groups", warnings, StringComparison.Ordinal);
        Assert.Contains("PreviewDiagnosticSeverity", warnings, StringComparison.Ordinal);
        Assert.Contains("PreviewDiagnosticSummaryService", summaries, StringComparison.Ordinal);
        Assert.Contains("OccurrenceCount", summaries, StringComparison.Ordinal);
    }

    private static string Read(string root, params string[] parts) =>
        File.ReadAllText(Path.Combine(new[] { root }.Concat(parts).ToArray()));
}
