namespace KKL.WordStudio.Architecture.Tests;

using Xunit;

public sealed class Sprint21ColumnSelectionArchitectureTests
{
    [Fact]
    public void MappingSurface_ProvidesSingleClickCheckboxAndBulkSelectionWithoutDeletingSourceColumns()
    {
        var root = SolutionRootLocator.Find();
        var xaml = Read(root, "src", "KKL.WordStudio.UI", "Views", "ExcelWorkspaceView.xaml");
        var headerSurface = Read(root, "src", "KKL.WordStudio.UI", "Views", "ExcelWorkspaceView.Sprint23.cs");
        var displayOrder = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "ExcelWorkspaceViewModel.DisplayOrder.cs");
        var row = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "ColumnMappingRowViewModel.cs");
        var viewModel = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "ExcelWorkspaceViewModel.TransferPlacement.cs");
        var coordinator = Read(root, "src", "KKL.WordStudio.Application", "Transfer", "ExcelTransferPlacementCoordinator.cs");

        Assert.Contains("CanUserSortColumns=\"False\"", xaml, StringComparison.Ordinal);
        Assert.Contains("AutoGeneratedColumns=\"WorkingDataGrid_AutoGeneratedColumnsV23\"", xaml, StringComparison.Ordinal);
        Assert.Contains("var include = new CheckBox", headerSurface, StringComparison.Ordinal);
        Assert.Contains("ToolTip = \"Bu sütunu Word tablosuna aktar\"", headerSurface, StringComparison.Ordinal);
        Assert.Contains("SetColumnIncluded(identity, true)", headerSurface, StringComparison.Ordinal);
        Assert.Contains("SetColumnIncluded(identity, false)", headerSurface, StringComparison.Ordinal);
        Assert.Contains("SynchronizeTransferColumnOrder", headerSurface, StringComparison.Ordinal);
        Assert.Contains("OrderBy(column => column.DisplayIndex)", headerSurface, StringComparison.Ordinal);
        Assert.Contains("option.SourceOrder = displayIndex", displayOrder, StringComparison.Ordinal);
        Assert.Contains("[ObservableProperty]", row, StringComparison.Ordinal);
        Assert.Contains("private bool _isIncluded;", row, StringComparison.Ordinal);
        Assert.Contains("PersistTransferColumnOptions", viewModel, StringComparison.Ordinal);
        Assert.Contains("selectedOptions.Count == 0", viewModel, StringComparison.Ordinal);
        Assert.Contains("table.Caption = ResolveRawCaption", coordinator, StringComparison.Ordinal);
        Assert.Contains("ReportHeadingNumberingService.Renumber(report)", coordinator, StringComparison.Ordinal);

        Assert.DoesNotContain("Content=\"Sütunları Eşle\"", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("SÜTUNLARI SEÇ VE EŞLE", xaml, StringComparison.Ordinal);
        Assert.DoesNotContain("File.Write", viewModel, StringComparison.Ordinal);
        Assert.DoesNotContain("WorkingData.Columns.Remove", viewModel, StringComparison.Ordinal);
    }

    [Fact]
    public void TransferDecorator_FiltersBothSourceRangeAndWorkingDataThenDelegatesToExistingService()
    {
        var root = SolutionRootLocator.Find();
        var decorator = Read(root, "src", "KKL.WordStudio.Application", "Transfer", "ColumnSelectionExcelReportTransferService.cs");
        var session = Read(root, "src", "KKL.WordStudio.Application", "Transfer", "ColumnTransferSelectionSession.cs");
        var app = Read(root, "src", "KKL.WordStudio.UI", "App.xaml.cs");

        Assert.Contains("request.WorkingDataColumns is { Count: > 0 }", decorator, StringComparison.Ordinal);
        Assert.Contains("BuildSourceRangeProjection", decorator, StringComparison.Ordinal);
        Assert.Contains("FilterWorkingDataColumns", decorator, StringComparison.Ordinal);
        Assert.Contains("return inner.Transfer", decorator, StringComparison.Ordinal);
        Assert.Contains("OriginalSourceColumn", decorator, StringComparison.Ordinal);
        Assert.Contains("ConcurrentDictionary", session, StringComparison.Ordinal);
        Assert.Contains("Runtime-only", session, StringComparison.Ordinal);
        Assert.Contains("ColumnSelectionExcelReportTransferService", app, StringComparison.Ordinal);
        Assert.Contains("IColumnTransferSelectionSession", app, StringComparison.Ordinal);

        Assert.DoesNotContain("Domain.Elements.TableElement", decorator, StringComparison.Ordinal);
        Assert.DoesNotContain("WordprocessingDocument", decorator, StringComparison.Ordinal);
        Assert.DoesNotContain("IExcelWorkbookReader", decorator, StringComparison.Ordinal);
    }

    [Fact]
    public void ColumnSelection_DoesNotAddPersistenceToDomain()
    {
        // Historical method name is kept because the baseline inventory tracks
        // test identities. Sprint 23 intentionally persists worksheet transfer
        // preferences, but only on the existing ColumnMapping configuration;
        // report elements and Excel file-writing paths must remain untouched.
        var root = SolutionRootLocator.Find();
        var mapping = Read(root, "src", "KKL.WordStudio.Domain", "DataSources", "ColumnMapping.cs");
        var table = Read(root, "src", "KKL.WordStudio.Domain", "Elements", "TableElement.cs");
        var transferViewModel = Read(root, "src", "KKL.WordStudio.UI", "ViewModels", "ExcelWorkspaceViewModel.TransferPlacement.cs");

        Assert.Contains("public bool IsIncluded { get; set; } = true;", mapping, StringComparison.Ordinal);
        Assert.Contains("public string? SemanticRole { get; set; }", mapping, StringComparison.Ordinal);
        Assert.Contains("public string? DisplayHeader { get; set; }", mapping, StringComparison.Ordinal);
        Assert.DoesNotContain("IsIncluded", table, StringComparison.Ordinal);
        Assert.DoesNotContain("SemanticRole", table, StringComparison.Ordinal);
        Assert.DoesNotContain("File.Write", transferViewModel, StringComparison.Ordinal);
        Assert.DoesNotContain("SpreadsheetDocument.Create", transferViewModel, StringComparison.Ordinal);
    }

    private static string Read(string root, params string[] parts) =>
        File.ReadAllText(Path.Combine(new[] { root }.Concat(parts).ToArray()));
}
